/**
 * @fileoverview gRPC-Web generated client stub for example.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.20.3
// source: example.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.example = {};
proto.example.proto = require('./example_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.example.proto.ExampleServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.example.proto.ExampleServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.example.proto.GetExampleDataRequest,
 *   !proto.example.proto.GetExampleDataResponse>}
 */
const methodDescriptor_ExampleService_GetExampleData = new grpc.web.MethodDescriptor(
  '/example.proto.ExampleService/GetExampleData',
  grpc.web.MethodType.UNARY,
  proto.example.proto.GetExampleDataRequest,
  proto.example.proto.GetExampleDataResponse,
  /**
   * @param {!proto.example.proto.GetExampleDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.example.proto.GetExampleDataResponse.deserializeBinary
);


/**
 * @param {!proto.example.proto.GetExampleDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.example.proto.GetExampleDataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.example.proto.GetExampleDataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.example.proto.ExampleServiceClient.prototype.getExampleData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/example.proto.ExampleService/GetExampleData',
      request,
      metadata || {},
      methodDescriptor_ExampleService_GetExampleData,
      callback);
};


/**
 * @param {!proto.example.proto.GetExampleDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.example.proto.GetExampleDataResponse>}
 *     Promise that resolves to the response
 */
proto.example.proto.ExampleServicePromiseClient.prototype.getExampleData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/example.proto.ExampleService/GetExampleData',
      request,
      metadata || {},
      methodDescriptor_ExampleService_GetExampleData);
};


module.exports = proto.example.proto;

